name: paleoPCA-Cookbook
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - jupyterlab-myst
  - pip
  - pandas
  - s3fs
  - fsspec
  - numpy
  - cartopy
  - matplotlib
  - pip:
    - pyleoclim
    - xarray
    - h5netcdf
    - nc-time-axis
    - eofs
    - h5py
  - mystmd
  
